swagger: "2.0"

info:
  version: "1.0"
  title: Artrunde Public API
  license:
    name: MIT
host: api-rodin-dev.artrunde.com

basePath: /v1
schemes:
  - https

paths:

  /admin/debug:
    get:
      summary: "Get debug information"
      description: "Get debug information about query"
      operationId: "debugUrl"
      tags:
          - "Debug"
      produces:
        - application/json
      responses:
        200:
          description: "Debug information"
          schema:
            $ref: "#/definitions/Debug"

  /admin/tags:
    post:
      tags:
      - "Tag"
      summary: "Create a tag"
      description: "Create a new tag with labels."
      operationId: "createNewTag"
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: "body"
        name: "body"
        description: "Tag object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/TagInput"
      responses:
        200:
          description: "Successful result"
          schema:
            $ref: "#/definitions/Tag"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/Error"

  /admin/tags/{tag_id}:
    get:
      tags:
        - "Tag"
      summary: "Get tag"
      description: "Retrieve data about a specific tag"
      operationId: "getTagByID"
      produces:
        - application/json
      parameters:
        - name: "tag_id"
          in: path
          description: "Tag unique identifier"
          required: true
          type: string
          x-example: "tagid"
      responses:
        200:
          description: "Successful result"
          schema:
            $ref: "#/definitions/Tag"
        404:
          description: "Item not found"
          schema:
            $ref: "#/definitions/Error"
    delete:
      tags:
        - "Tag"
      summary: "Delete tag"
      description: "Delete a specific tag and all its labels"
      operationId: "deleteTagByID"
      produces:
        - application/json
      parameters:
        - name: "tag_id"
          in: path
          description: "Tag unique identifier"
          required: true
          type: string
          x-example: "tagid"
      responses:
        200:
          description: "Successful result"
          schema:
            properties:
              tag_id:
                type: string
        404:
          description: "Item not found"
          schema:
            $ref: "#/definitions/Error"

### ref-compiler: BEGIN
definitions:

  ErrorMessages:
    type: object
    properties:
      text:
        type: string
        example: "Item(s) not found"
      type:
        type: string
        example: "warning"

  Error:
    type: object
    properties:
      meta:
        type: object
        properties:
          statusCode:
            type: integer
            enum:
              - 400
              - 404
          statusMessage:
            type: string
            example: "Item(s) not found"
          count:
            type: integer
            example: 1
          version:
            type: string
            example: "v1.1.0"
          environment:
            type: string
            example: "dev"
          stage:
            type: string
            example: "stagename"
          build:
            type: string
            example: "555"
      messages:
        type: array
        items:
          $ref: "#/definitions/ErrorMessages"
      data:
        type: string

  Debug:
    type: object
    properties:
      event_params:
        type: object
    required:
      - "event_params"

  TagLabel:
    type: object
    properties:
      category:
        type: string
        enum:
          - "countryname"
      locale:
        type: string
        enum:
          - "en"
          - "dk"
      label:
        type: string
        example: "Berlin"
    required:
      - "locale"
      - "label"

  TagInput:
    type: object
    properties:
      category:
        type: string
        enum:
          - "countryname"
      labels:
        type: array
        minItems: 0
        maxItems: 2
        uniqueItems: true
        items:
          $ref: "#/definitions/TagLabel"
    required:
      - "category"
      - "labels"

  Tag:
    type: object
    properties:
      tag_id:
        type: string
      category:
        type: string
        enum:
          - "countryname"
      labels:
        type: array
        minItems: 0
        maxItems: 2
        uniqueItems: true
        items:
          $ref: "#/definitions/TagLabel"
    required:
      - "tag_id"
      - "category"
      - "labels"